import { test, expect, scrollToSection } from './fixtures';

const ANSWER = {
  answer: 'He built LangGraph agents for access reviews [1].',
  mode: 'generated',
  reason: 'generated',
  model: 'claude-haiku-4-5',
  sources: [
    { n: 1, id: 'exp-wells-fargo', title: 'Full Stack Python AI Developer, Wells Fargo', section: 'Experience', score: 7.1, text: 'At Wells Fargo Harshith built IAM Remediation.' },
  ],
  timings: { retrieve_ms: 0.2, total_ms: 812.4 },
};

test('project card links to the live /ask demo', async ({ page }) => {
  await page.goto('/');
  await scrollToSection(page, 'projects');
  const card = page.locator('.project-card', { hasText: 'Ask My Portfolio' });
  await expect(card).toBeVisible();
  await expect(card.getByRole('link', { name: 'Live Demo' })).toHaveAttribute('href', '/ask');
});

test('asks a question with a solved bot check and shows the cited answer', async ({ page }) => {
  let posted: { question?: string; proof?: { token: string; counter: number } } | undefined;
  await page.route('**/api/ask', route => {
    if (route.request().method() === 'GET') return route.fulfill({ json: { token: 'test-token', bits: 4 } });
    posted = route.request().postDataJSON();
    return route.fulfill({ json: ANSWER });
  });

  // vite preview serves the page as ask.html; Vercel serves it at /ask.
  await page.goto(process.env.BASE_URL ? '/ask' : '/ask.html');
  await page.getByRole('button', { name: 'Has he worked in banking?' }).click();

  await expect(page.getByText('He built LangGraph agents for access reviews')).toBeVisible();
  await expect(page.getByText('Generated by claude-haiku-4-5')).toBeVisible();
  expect(posted?.question).toBe('Has he worked in banking?');
  expect(posted?.proof?.token).toBe('test-token');

  await page.getByRole('button', { name: 'Show source 1' }).click();
  await expect(page.getByText('At Wells Fargo Harshith built IAM Remediation.')).toBeVisible();
});
