import { useEffect, useRef, useState } from 'react';
import { track } from '@vercel/analytics';
import { GitHubIcon } from '../components/Icons';
import { solveChallenge, type Proof } from './pow';
import './AskApp.css';

interface Source {
  n: number;
  id: string;
  title: string;
  section: string;
  score: number;
  text: string;
}

interface AskResponse {
  answer: string;
  mode: 'generated' | 'retrieval';
  reason: 'generated' | 'no_match' | 'no_key' | 'bot_check_failed' | 'daily_cap' | 'model_error';
  model: string | null;
  sources: Source[];
  timings: { retrieve_ms: number; total_ms: number };
}

type Turn =
  | { role: 'user'; text: string }
  | { role: 'assistant'; data: AskResponse }
  | { role: 'error'; text: string };

const SUGGESTIONS = [
  'What AI and agentic work has he done?',
  'Has he worked in banking?',
  'What cloud and DevOps tools does he use?',
  'Tell me about Event Syncer',
  'How can I contact him?',
];

const MAX_QUESTION = 300;
const SOURCE_URL = 'https://github.com/Harshith5299/portfolio/blob/main/api/_rag.py';

const PIPELINE = [
  { label: 'Retrieve', desc: 'BM25 ranks 16 passages written from this site: experience, skills, projects.' },
  { label: 'Ground', desc: 'The top 4 passages are numbered and passed to the model as the only allowed context.' },
  { label: 'Generate', desc: 'Claude answers in 2 to 4 sentences with [n] citations, or says it does not know.' },
  { label: 'Protect', desc: 'An invisible proof-of-work check and daily caps keep bots from running up model costs.' },
  { label: 'Fallback', desc: 'If the model is unavailable or a check fails, the best-matching sentences are returned extractively.' },
];

/** Render "[1]" markers in an answer as citation chips that highlight the matching source. */
function AnswerText({ text, onCite }: { text: string; onCite: (n: number) => void }) {
  const parts = text.split(/(\[\d+\])/g);
  return (
    <p className="ask__answer">
      {parts.map((part, i) => {
        const m = /^\[(\d+)\]$/.exec(part);
        if (!m) return <span key={i}>{part}</span>;
        const n = Number(m[1]);
        return (
          <button key={i} type="button" className="ask__cite" onClick={() => onCite(n)} aria-label={`Show source ${n}`}>
            {n}
          </button>
        );
      })}
    </p>
  );
}

function AssistantTurn({ data }: { data: AskResponse }) {
  const [active, setActive] = useState<number | null>(null);
  const maxScore = Math.max(...data.sources.map(s => s.score), 1);

  return (
    <div className="ask__bubble ask__bubble--bot">
      <AnswerText text={data.answer} onCite={setActive} />

      {data.sources.length > 0 && (
        <ol className="ask__sources">
          {data.sources.map(s => (
            <li key={s.id} className={`ask__source${active === s.n ? ' ask__source--active' : ''}`}>
              <button type="button" className="ask__source-head" onClick={() => setActive(active === s.n ? null : s.n)}>
                <span className="ask__source-n">{s.n}</span>
                <span className="ask__source-title">{s.title}</span>
                <span className="ask__source-section">{s.section}</span>
                <span className="ask__score" title={`BM25 score ${s.score}`}>
                  <span style={{ width: `${(s.score / maxScore) * 100}%` }} />
                </span>
              </button>
              {active === s.n && <p className="ask__source-text">{s.text}</p>}
            </li>
          ))}
        </ol>
      )}

      <div className="ask__meta">
        <span className={`ask__mode ask__mode--${data.mode}`}>
          {data.mode === 'generated' ? `Generated by ${data.model ?? 'Claude'}` : 'Retrieval only'}
        </span>
        <span>retrieve {data.timings.retrieve_ms} ms</span>
        <span>total {data.timings.total_ms} ms</span>
      </div>
    </div>
  );
}

export function AskApp() {
  const [turns, setTurns] = useState<Turn[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);
  // Bot check solved in the background, so it's ready before the visitor asks.
  const proofRef = useRef<Promise<Proof | null> | null>(null);

  useEffect(() => {
    proofRef.current = solveChallenge();
  }, []);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' });
  }, [turns, loading]);

  async function ask(question: string) {
    const q = question.trim();
    if (!q || loading) return;
    setInput('');
    setTurns(t => [...t, { role: 'user', text: q }]);
    setLoading(true);
    try {
      const proof = await (proofRef.current ?? solveChallenge());
      proofRef.current = solveChallenge(); // each proof is single-use; start the next one
      const res = await fetch('/api/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question: q, proof }),
      });
      const body = await res.json().catch(() => null);
      if (!res.ok || !body) throw new Error(body?.error ?? 'The assistant is unavailable right now.');
      const data = body as AskResponse;
      track('Ask Answered', { mode: data.mode, reason: data.reason, botCheck: proof ? 'solved' : 'unsolved' });
      setTurns(t => [...t, { role: 'assistant', data }]);
    } catch (err) {
      const text = err instanceof Error ? err.message : 'Something went wrong.';
      track('Ask Failed', { error: text.slice(0, 100) });
      setTurns(t => [...t, { role: 'error', text }]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="ask">
      <header className="ask__header container">
        <a href="/" className="ask__back">← Harshith Chittajallu</a>
        <a href={SOURCE_URL} target="_blank" rel="noopener noreferrer" className="btn btn-ghost btn--sm">
          <GitHubIcon />
          Source
        </a>
      </header>

      <main className="ask__layout container">
        <section className="ask__chat" aria-label="Ask My Portfolio chat">
          <div className="ask__intro">
            <span className="section-label">Gen AI demo · RAG</span>
            <h1 className="ask__title">Ask My <span>Portfolio</span></h1>
            <p className="ask__lede">
              Ask anything a recruiter would. Answers are grounded only in this site's content, and every claim
              cites the passage it came from.
            </p>
          </div>

          <div className="ask__log" aria-live="polite">
            {turns.length === 0 && (
              <div className="ask__suggestions">
                {SUGGESTIONS.map(s => (
                  <button key={s} type="button" className="ask__chip" onClick={() => ask(s)}>
                    {s}
                  </button>
                ))}
              </div>
            )}
            {turns.map((turn, i) =>
              turn.role === 'user' ? (
                <div key={i} className="ask__bubble ask__bubble--user">{turn.text}</div>
              ) : turn.role === 'assistant' ? (
                <AssistantTurn key={i} data={turn.data} />
              ) : (
                <div key={i} className="ask__bubble ask__bubble--error">{turn.text}</div>
              ),
            )}
            {loading && (
              <div className="ask__bubble ask__bubble--bot ask__thinking" aria-label="Thinking">
                <span />
                <span />
                <span />
              </div>
            )}
            <div ref={endRef} />
          </div>

          <form
            className="ask__form"
            onSubmit={e => {
              e.preventDefault();
              ask(input);
            }}
          >
            <input
              className="ask__input"
              value={input}
              onChange={e => setInput(e.target.value)}
              maxLength={MAX_QUESTION}
              placeholder="e.g. What has he built with LangGraph?"
              aria-label="Your question"
            />
            <button type="submit" className="btn btn-primary" disabled={loading || !input.trim()}>
              Ask
            </button>
          </form>
        </section>

        <aside className="ask__how" aria-label="How it works">
          <h2>How it works</h2>
          <ol>
            {PIPELINE.map((step, i) => (
              <li key={step.label}>
                <span className="ask__how-n">{i + 1}</span>
                <div>
                  <strong>{step.label}</strong>
                  <p>{step.desc}</p>
                </div>
              </li>
            ))}
          </ol>
          <div className="card-tags">
            {['Python', 'RAG', 'BM25', 'Claude API', 'Vercel Functions', 'React'].map(t => (
              <span key={t} className="card-tag">{t}</span>
            ))}
          </div>
        </aside>
      </main>
    </div>
  );
}
